#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 2.0.0-{build}

nuget:  
  disable_publish_on_pr: true

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

# to run your custom scripts instead of automatic MSBuild
build_script:
  - dotnet build -c Release

# scripts to run after build
after_build:
  - dotnet pack src\Owin.Token.AspNetCore -c Release -o "..\..\artifacts" --no-build --no-restore

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  # pushing a single file
  - path: .\artifacts\**\*.nupkg
    name: NuGet

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

# providers: Local, FTP, WebDeploy, AzureCS, AzureBlob, S3, NuGet, Environment
# provider names are case-sensitive!
deploy:
  - provider: NuGet
    api_key:
      secure: PbUCzCO/I+rT1PDa406E5LLeazxk2+a42ivh/Yer4Fpmt6EfstZ5W5yl5GygLKX170KEG58gKdZTKpWCoDn9JA==
    skip_symbols: true
    on:
      APPVEYOR_REPO_TAG: true